### ISSUE TITLE
Auto-convert smart quotes

### ISSUE THREAD

**Issue by chipzoller** [benbalter/word-to-markdown#105]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

Smart quotes written in MS Word docs are not converted to straight quotes.

### Describe the solution you'd like

Auto detect and convert smart quotes and apostrophes to straight quotes and apostrophes.

### Describe alternatives you've considered

Manually copy-and-paste Word content into VS Code where Markdown is rendered properly.

**Comment by davwheat** [comment]
Not stale!
