### ISSUE TITLE
Newlines within tables result in invalid markdown

### ISSUE THREAD

**Issue by joshmgross** [benbalter/word-to-markdown#185]
### Describe the bug

When a word doc table includes newlines, the resulting markdown keeps those newlines. Markdown tables can't contain newlines, so this results in a broken table.

[table.docx](https://github.com/benbalter/word-to-markdown/files/13734313/table.docx)

### Steps to reproduce the behavior

1. Create a word document with a table

I've modified the [current table test fixture](https://github.com/benbalter/word-to-markdown/blob/main/test/fixtures/table.docx) to include some rows with newlines:
[table.docx](https://github.com/benbalter/word-to-markdown/files/13734313/table.docx)

If you don't want to open that file for security reasons, it looks like this:

![a screenshot of a table in a word document](https://github.com/benbalter/word-to-markdown/assets/16631042/9742c643-2d79-4960-9930-24c8970091f5)

2. Save the document
3. Convert the document to markdown

I've used https://word2md.com/, but you can use this library directly to achieve the same result.

**Raw Markdown**
```md
| **Foo** | **Bar** |
| --- | --- |
| One | Two |
| Three | Four |
| Five
Six
Seven | Row

With

 Newlines |
```

--- 
**Rendered Markdown**
| **Foo** | **Bar** |
| --- | --- |
| One | Two |
| Three | Four |
| Five
Six
Seven | Row

With

 Newlines |

---

### Expected behavior

The converted document includes a valid markdown table.

Open to suggestions on whether the newlines should be removed or replaced with `<br>` to preserve the lines in a markdown compatible way. 

**Expected Raw Markdown**

```md
| **Foo** | **Bar** |
| --- | --- |
| One | Two |
| Three | Four |
| Five<br><br>Six<br><br>Seven | Row<br><br>With<br><br>Newlines |
```
---
**Expected Rendered Markdown**

| **Foo** | **Bar** |
| --- | --- |
| One | Two |
| Three | Four |
| Five<br><br>Six<br><br>Seven | Row<br><br>With<br><br>Newlines |

**Comment by benbalter** [comment]
Thanks for the bug report @joshmgross. I agree with the expected behavior (although I'm not 100% sure how to cleanly implement it).

**Comment by joshmgross** [comment]
I could not figure out how to cleanly fix this, I imagine it would take some changes to `reverse_markdown` which doesn't appear to be actively maintained.

#187 contains a very hacky solution as an alternative.

**Comment by benbalter** [comment]
@joshmgross mind giving the "beta" version a try? https://word2md.com. It _should_ properly respect line breaks now.

**Comment by joshmgross** [comment]
| **Foo** | **Bar** |
| --- | --- |
| One | Two |
| Three | Four |
| Five<br><br>Six<br><br>Seven | Row  <br><br>With  <br><br/>Newlines |


Looks great, thanks @benbalter!

The `word2md.com` rendered view seems to ignore the breaks but the markdown itself looks valid.
