### ISSUE TITLE
Internal Server Error (document attached)

### ISSUE THREAD

**Issue by ajb** [benbalter/word-to-markdown#26]
https://www.dropbox.com/s/b0gqbqt3ujiqpva/RELEASE%20AND%20PERMISSION%20TO%20USE%20ORGANIZATION%20LOGO.docx

**Comment by benbalter** [comment]
The issue was that it didn't like files with spaces due to how we were shelling out to the sub process. Fixed via https://github.com/benbalter/word-to-markdown/pull/42 and tested in https://github.com/benbalter/word-to-markdown/commit/75221422059bdf77430c2f1dda492ee728b9c7ac.
