### ISSUE TITLE
Cannot find Soffice on Windows

### ISSUE THREAD

**Issue by pyin222** [benbalter/word-to-markdown#37]
Thanks for this cool little tool and a new to Ruby gem so I will apologize up front if this is an easy fix. Trying to convert a bunch of .docx files to markdown to publish in mkdocs. I've installed gem and when i run to command "w2m /path/todocument.docx" I get the below error:

C:\Users\pyin>w2m c:/users/pyin/desktop/temp/yourwaytest2.docx
C:/Ruby193/lib/ruby/gems/1.9.1/gems/word-to-markdown-1.1.0/lib/word-to-markdown.
rb:59:in ``': No such file or directory - C:\Program Files (x86)\LibreOffice 4\p
rogram/soffice.EXE --headless --convert-to html 'c:/users/pyin/desktop/temp/your
waytest2.docx' --outdir C:/Users/pyin/AppData/Local/Temp/d20141203-2896-oe614b (
Errno::ENOENT)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/word-to-markdown-1.1.0/lib/word
-to-markdown.rb:59:in `run_command'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/word-to-markdown-1.1.0/lib/word
-to-markdown/document.rb:88:in `raw_html'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/word-to-markdown-1.1.0/lib/word
-to-markdown/document.rb:20:in `tree'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/word-to-markdown-1.1.0/lib/word
-to-markdown/converter.rb:79:in `semanticize_font_styles!'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/word-to-markdown-1.1.0/lib/word
-to-markdown/converter.rb:19:in `convert!'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/word-to-markdown-1.1.0/lib/word
-to-markdown.rb:29:in `initialize'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/word-to-markdown-1.1.0/bin/w2m:
10:in `new'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/word-to-markdown-1.1.0/bin/w2m:
10:in `<top (required)>'
        from C:/Ruby193/bin/w2m:23:in `load'
        from C:/Ruby193/bin/w2m:23:in `<main>'

Any advice on this?

Thanks.

Phillip

**Comment by vasundhar** [comment]
Problem is with the C:\Program Files (x86)\LibreOffice 4\p rogram"/"soffice.EXE Did you notice the unix style directory separator ? Where its looking for the path ? I am not sure in windows world path delimiter is taken strictly or not.

**Comment by benbalter** [comment]
I believe it may be associated with the forward slash in the path, but it's built using `File.join` which should account for Windows automatically.  Does it work on any Windows systems?

If anyone can debug this, or confirm the issue, it'd go a long way to get this resolved. I can try to find and set up a VM this weekend, but that's a lot of yak shaving if a windows user can investigate.

**Comment by benbalter** [comment]
The way the Gem finds the path to `soffice.exe` and calls sub processes has been completely rewritten in https://github.com/benbalter/word-to-markdown/pull/42. There's also now a windows-based CI to confirm things work on windows. This (and other windows pain points) should be fixed in the next release.

**Comment by benbalter** [comment]
[v1.1.1](https://github.com/benbalter/word-to-markdown/releases/tag/v1.1.1) is out with a bunch of windows fixes. Please holler if anything's still wonky.
