### ISSUE TITLE
Better image handling options: drop, upload, data-uri

### ISSUE THREAD

**Issue by Scotchester** [benbalter/word-to-markdown#45]
It'd be nice if there was an option to disable the conversion of images to data URIs. They can be so large they're hard to easily remove from the output, in some cases :)

Thanks for this excellent tool!

**Comment by benbalter** [comment]
@Scotchester what would you want the output to be? Upload to someplace like `cl.ly`? Drop the image?

**Comment by Scotchester** [comment]
Good question!

In my case, I was converting the doc to a MD file for publication on a GH Pages site, and I added the images to that repo, so I was just suggesting dropping them entirely*. But I'm not sure if that's the most common use case.

The auto-upload idea is a nice one. All three options (drop, upload, data URI) would be nice to have, eventually.

_* In the case of dropping, it might be nice to include a note that an image used to be here in the form of a Markdown image tag, so you can easily remember where to insert the final location of the image._

**Comment by benbalter** [comment]
@Scotchester think that's valid. Thinking an option to choose between drop, data-uri, and upload is the way to go. Will leave this open until someone (myself included) can take a pass.

**Comment by spajus** [comment]
Quick hack for those who want images removed:

```ruby
# lib/converters/remove_img.rb
module ReverseMarkdown                                                                                         
  module Converters                                                                                            
    class RemoveImg < Base                                                                                     
      def convert(node, state = {})                                                                            
        "!!! Image removed. Title: #{extract_title(node)}. Alt: #{node['alt']} !!!"
      end                                                                                                      
    end                                                                                                        
    unregister :img # remove original converter                                                                
    register :img, RemoveImg.new                                                                               
  end                                                                                                          
end     
```
