### ISSUE TITLE
Bug: Link at list won't show

### ISSUE THREAD

**Issue by androchentw** [benbalter/word-to-markdown#46]
I'm using Mac OSX with Word version 14.4.0
I could successfully transfer the file, while there is a little bug.

For example
> [word-to-markdown](https://github.com/benbalter/word-to-markdown)
> - [word-to-markdown](https://github.com/benbalter/word-to-markdown)

would turn out to be

```
[word-to-markdown](https://github.com/benbalter/word-to-markdown)
- word-to-markdown
```

, which I guess this may be caused by indent.

Please tell me if I'm misunderstanding something, and how to fix it to accomplish what I expected it should be.
Thanks for this great repo!

**Comment by benbalter** [comment]
Are you able to isolate the troublesome part of the document and upload it somewhere? That way we can build a test against it, and can ensure it works going forward.

**Comment by androchentw** [comment]
Sure!
Please check [2015_0321_word_to_markdown_bug_case](https://drive.google.com/file/d/0B29X9yW5w71kY3hsTmVyQWdvT3c/view?usp=sharing) out.

**Comment by benbalter** [comment]
Fixed!

![screen shot 2015-03-21 at 1 53 49 pm](https://cloud.githubusercontent.com/assets/282759/6766169/c19e8fd8-cfd1-11e4-90e2-91f60f4324c8.png)
