### ISSUE TITLE
Bug: Encoding issue only on web demo

### ISSUE THREAD

**Issue by androchentw** [benbalter/word-to-markdown#49]
I got some encoding issue when upload the file on website, which works fine on command line.

![web render](https://cloud.githubusercontent.com/assets/2317501/6767680/4c970690-d079-11e4-93e7-21513d9f64d2.png)
![gem render](https://cloud.githubusercontent.com/assets/2317501/6767681/4c993d84-d079-11e4-9a60-f8345b716590.png)

Bug case: [2015_0322_word_to_markdown_bug_case.docx](https://drive.google.com/file/d/0B29X9yW5w71kdjloMDdKSWxSelU/view?usp=sharing)

**Comment by benbalter** [comment]
I believe this should now be fixed.

**Comment by androchentw** [comment]
Thank you for the effort and this great library!
