### ISSUE TITLE
Its doesnt even convert at all. Shows weird errors.

### ISSUE THREAD

**Issue by gauthamilango** [benbalter/word-to-markdown#52]
These are the errors I received:

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:211:in `spawn': no implicit conversion of nil into String (TypeError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:211:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:206:in `popen2e'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:372:in `capture2e'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/lib/word-to-markdown.rb:67:in `run_command'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/lib/word-to-markdown/document.rb:90:in `raw_html'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/lib/word-to-markdown/document.rb:58:in `normalized_html'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/lib/word-to-markdown/document.rb:20:in `tree'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/lib/word-to-markdown/converter.rb:78:in `semanticize_font_styles!'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/lib/word-to-markdown/converter.rb:18:in `convert!'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/lib/word-to-markdown.rb:31:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/bin/w2m:14:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/bin/w2m:14:in `<top (required)>'
	from /usr/bin/w2m:23:in `load'
	from /usr/bin/w2m:23:in `<main>'

**Comment by benbalter** [comment]
Do you have LibreOffice installed? What operating system are you using?

**Comment by gauthamilango** [comment]
My operating system is OSX 10.10.3 . And no I don't have LibreOffice installed. Thanks for the quick comment on my issue!

**Comment by cameronmcefee** [comment]
Ran into this issue myself. Installing the latest from http://www.libreoffice.org/ fixed things.

**Comment by benbalter** [comment]
The latest version should check if libre office is installed, and provide a descriptive error, if not.
