### ISSUE TITLE
encounter an error while converting

### ISSUE THREAD

**Issue by sandbeach** [benbalter/word-to-markdown#53]
Seems it will first convert to html?

jacksondeMacBook-Pro:word2markdown jackson$ w2m abc0.0.11.docx 
/Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/lib/word-to-markdown/document.rb:91:in `read': No such file or directory - /var/folders/vn/81b5g27170j8bqsydq6w7n1w0000gn/T/d20150531-1488-ogxosw/abc0.0.11.html (Errno::ENOENT)
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/lib/word-to-markdown/document.rb:91:in `raw_html'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/lib/word-to-markdown/document.rb:58:in `normalized_html'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/lib/word-to-markdown/document.rb:20:in `tree'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/lib/word-to-markdown/converter.rb:78:in `semanticize_font_styles!'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/lib/word-to-markdown/converter.rb:18:in `convert!'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/lib/word-to-markdown.rb:31:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/bin/w2m:14:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.2/bin/w2m:14:in `<top (required)>'
	from /usr/bin/w2m:23:in `load'
	from /usr/bin/w2m:23:in `<main>'

**Comment by benbalter** [comment]
@sandbeach was LibreOffice GUI open, by chance, when you ran this?
