### ISSUE TITLE
Image handling?

### ISSUE THREAD

**Issue by bitnumus** [benbalter/word-to-markdown#69]
Hi, this may be more a question rather than an issue but wasn't sure of a better place to ask.

Currently i'm just testing this code, would be perfect for me and save a lot of time. I just have a question about image handling.

I'm converting like this:

w2c /path/to/file.doc >> new.md

However, images are spamming the code with hex or whatever it is :). How can i convert the images to a uri or something that'll point to a local file?

Many thanks

**Comment by benbalter** [comment]
> However, images are spamming the code with hex or whatever it is :). How can i convert the images to a uri or something that'll point to a local file?

It's Base64 encoded, to keep the images *within* the document. If you'd like, you can pull them out of the original `.docx` file, and save them to disk or upload them somewhere. You'll just need to replace the src for the image in the resulting markdown with image you pulled out.
