### ISSUE TITLE
Conversion error

### ISSUE THREAD

**Issue by iangilman** [benbalter/word-to-markdown#74]
I love this library, and I've been using the demo version online, but I'm finally getting around to setting it up locally. I installed the gem and Libre Office (I'm on a Mac running Sierra), but when I try to convert I get this:

```
leo:docs iangilman$ w2m mydoc.docx
/Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.7/lib/word-to-markdown/document.rb:92:in `raw_html': Failed to convert /Users/iangilman/work/docs/mydoc.docx (WordToMarkdown::Document::ConverstionError)
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.7/lib/word-to-markdown/document.rb:59:in `normalized_html'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.7/lib/word-to-markdown/document.rb:21:in `tree'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.7/lib/word-to-markdown/converter.rb:78:in `semanticize_font_styles!'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.7/lib/word-to-markdown/converter.rb:18:in `convert!'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.7/lib/word-to-markdown.rb:45:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.7/bin/w2m:14:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/word-to-markdown-1.1.7/bin/w2m:14:in `<top (required)>'
	from /usr/local/bin/w2m:23:in `load'
	from /usr/local/bin/w2m:23:in `<main>'
```

The doc in question opens fine in Libre Office.

Any idea what is going wrong? Anything I can try to fix it? Thank you!

**Comment by iangilman** [comment]
Well, I never found a fix for this issue, but I've moved on to using another (Node-based) converter, so I guess we're done here. That said, I'd still be curious to know what the cause of this issue was.

**Comment by janeshdev** [comment]
I have seen the same behavior. What was the solution to this problem ?

**Comment by iangilman** [comment]
I never found a solution. I just moved on to https://www.npmjs.com/package/mammoth.

**Comment by janeshdev** [comment]
Thanks for pointing to mammoth. I ended up using `pandoc` to convert docs to markdown.
