### ISSUE TITLE
Error converting the file to markdown

### ISSUE THREAD

**Issue by janeshdev** [benbalter/word-to-markdown#76]
Hi I followed the procedure you described. I installed libreoffice and then installed gems. Then installed word-to-markdown using following command `gem install word-to-markdown`. 

Then I ran the command `w2m .\Desktop\part1.docx` as shown in image below and got the error. 

![image](https://user-images.githubusercontent.com/3325086/28850953-5acdd528-76d4-11e7-8a54-470fba77ccc9.png)

**Comment by benbalter** [comment]
The error states that `soffice` is not in your path. Is that possible?

**Comment by janeshdev** [comment]
Hi @benbalter  , thank you for your response. I added soffice in my path and I am still getting the same error. I am using windows platform.
