### ISSUE TITLE
ERROR:  Error installing word-to-markdown:

### ISSUE THREAD

**Issue by nrbray** [benbalter/word-to-markdown#78]
sudo gem install word-to-markdown
Fetching: mini_portile2-2.3.0.gem (100%)
Successfully installed mini_portile2-2.3.0
Fetching: nokogiri-1.8.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing word-to-markdown:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/nokogiri-1.8.1/ext/nokogiri
/usr/bin/ruby2.3 -r ./siteconf20171106-14125-1km0ne7.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/nokogiri-1.8.1 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.8.1/gem_make.out

```

current directory: /var/lib/gems/2.3.0/gems/nokogiri-1.8.1/ext/nokogiri
/usr/bin/ruby2.3 -r ./siteconf20171106-14125-1km0ne7.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

```

**Comment by nrbray** [comment]
Further installled:

> sudo apt-get install ruby-dev

Then:

sudo gem install zlib
Fetching: zlib-0.1.0.gem (100%)
ERROR:  Error installing zlib:
	zlib requires Ruby version >= 2.5.0dev.
ERROR:  Error installing word-to-markdown:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/nokogiri-1.8.1/ext/nokogiri
/usr/bin/ruby2.3 -r ./siteconf20171106-14491-rn3iu3.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.3.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***

[mkmf.log](https://github.com/benbalter/word-to-markdown/files/1447235/mkmf.log)

**Comment by benbalter** [comment]
@nrbray I believe the instructions in https://github.com/github/pages-gem/issues/133 may help resolve the issue.
