### ISSUE TITLE
Line changes in a table

### ISSUE THREAD

**Issue by RationalMatta** [benbalter/word-to-markdown#82]
Depending on what kind of line change you use in a table cell, it either is removed or turned to an actual line change that will break the table. It would be better to convert them to &lt;br&gt; or some other explicit linechange mechanism
[markdowntest.docx](https://github.com/benbalter/word-to-markdown/files/1866179/markdowntest.docx)

**Comment by anray** [comment]
Multiline text inside of a table cell makes the rest of the table fall apart. In fact this is an expected behaviour for markdown. But it would be nice if you implement automatic conversion of line breaks inside table cells into \<br\>.
