### ISSUE TITLE
Does not recognize bold plain text style

### ISSUE THREAD

**Issue by Ilias48rus** [benbalter/word-to-markdown#93]
Example [.docx](https://github.com/benbalter/word-to-markdown/files/2713771/t.docx) (prelast line not gets translated as bold
![pizmiszboldxwordtomarkdownconverter](https://user-images.githubusercontent.com/13949704/49819272-0e2bda00-fd86-11e8-80f0-0963cb62e882.PNG)
)

**Comment by dougrk** [comment]
I tried to reproduce this issue, but I got the following output for the file
```
# **t**

**t**

**t**

**t**

**t**

t

1
```
After the unexpected 1, it also printed some text that wasn't visible in the docx file, but it had links to a discord server, so I'll omit it here.

If I copy and paste the text in a new docx and save it, w2m produces the expected output and there is no extra text riding along

```
# **t**

**t**

**t**

**t**

**t**

t
```

**Comment by Ilias48rus** [comment]
@dougrk i just redownloaded the file and conversion resulted in completely same output as in the my screenshot

**Comment by dougrk** [comment]
It seems like this may be an issue specific to the herokuapp version then. When I commented yesterday, I had run w2m on MacOs. I got the same result today on Windows. When running on the web version, I can duplicate the results. If it is specific to the web version, I can't do anything. I'm not actually a maintainer of this project, I just go around hunting help-wanted issues :)

**Comment by Ilias48rus** [comment]
@dougrk specific to it then, if it works in the "main" one would be good to update the web (just restart using the repository files) (to dev), but i thing to note: the result you posted in 1st comment, hard to name correct.
