### ISSUE TITLE
Documentation: Installation

### ISSUE THREAD

**Issue by vatterspun** [benbalter/word-to-markdown#98]
Very interested in what you're doing, but could you give a little more step-by-step view of how to install / configure word-to-markdown?  I couldn't figure out how to do the "gem" function.  Is that a Linux-only thing?

**Comment by benbalter** [comment]
If you are not familiar with Ruby, Docker may be the easiest route. See https://github.com/benbalter/word-to-markdown#docker.

**Comment by vatterspun** [comment]
Ah, bit over my head.  Thanks.
