### ISSUE TITLE
images in the doc convert failed

### ISSUE THREAD

**Issue by xia0ming** [benbalter/word-to-markdown#99]
<img width="374" alt="image" src="https://user-images.githubusercontent.com/12314482/56420629-52e5f580-62d1-11e9-8090-f98c80b991f6.png">

it should be a base64 img, what is going wrong? help ToT

**Comment by mike-matera** [comment]
Hello! I'm seeing this too. When I use the web I get an `md` that has embedded images (which is what I would like). When I use the command line I get filenames. Any guidance would be greatly appreciated.

**Comment by mike-matera** [comment]
The problem is here: 

https://github.com/benbalter/word-to-markdown/blob/2473962911366eafea6fc8f45b3d912209f7949d/lib/word-to-markdown/document.rb#L107

I'm using soffice major version 6. It should be using the filter 'html:XHTML Writer File:UTF8' in order to get inline images.
